# ===========================================
# NAMESPACE & STORAGE
# ===========================================
apiVersion: v1
kind: Namespace
metadata:
  name: energy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: energetiscope-data
  namespace: energy
spec:
  storageClassName: local-path
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Gi