apiVersion: apps/v1
kind: Deployment
metadata:
  name: energetiscope-predict
  namespace: energy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energetiscope-predict
  template:
    metadata:
      labels:
        app: energetiscope-predict
    spec:
      containers:
        - name: api
          image: ghcr.io/mskazemi/energetiscope:latest
          imagePullPolicy: Always
          command: ["uvicorn"]
          args: ["predict_service:app", "--host", "0.0.0.0", "--port", "8000"]
          env:
            - name: ENCODER_PATH
              value: /app/artifacts/encoder.joblib
            - name: MODEL_PATH
              value: /app/artifacts/knn_energy.joblib
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: artifacts
              mountPath: /app/artifacts
      volumes:
        - name: artifacts
          persistentVolumeClaim:
            claimName: energetiscope-data
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: energetiscope-predict
#   namespace: energy
# spec:
#   type: ClusterIP
#   selector:
#     app: energetiscope-predict
#   ports:
#     - port: 80
#       targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: energetiscope-predict
  namespace: energy
spec:
  type: NodePort
  selector:
    app: energetiscope-predict
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30321  # Optional: choose between 30000â€“32767
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: energetiscope-predict
#   namespace: energy
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:
#     - host: energetiscope.local
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: energetiscope-predict
#                 port:
#                   number: 80
