apiVersion: apps/v1
kind: Deployment
metadata:
  name: energetiscope-collector
  namespace: energy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energetiscope-collector
  template:
    metadata:
      labels:
        app: energetiscope-collector
    spec:
      serviceAccountName: energetiscope-read
      containers:
        - name: collector
          image: ghcr.io/mskazemi/energetiscope:latest
          imagePullPolicy: Always
          args:
            - python
            - /app/k8s_collect.py
            - watch
            - --kinds
            - Deployment Job CronJob
            - --namespaces
            - energy
            - --emit-initial
            - --post
            - http://energetiscope-predict.energy.svc/predict
            - --suppress-tls-warnings
